#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh
$HOME/.config/scripts/dpms.sh
$HOME/.config/scripts/ConfMonitor.sh
$HOME/.config/scripts/picom.sh

#bspc monitor -d DSK DEV CLI IMG MOV MUS FAK DIS IRC TWT

bspc monitor HDMI-A-0 -d T1 T2 T3 T4 T5
bspc monitor DVI-D-0 -d T6 T7 T8 T9 T10
bspc monitor DisplayPort-0 -d T11 T12 T13 T14 T15

bspc config border_width            1
bspc config window_gap              4
bspc config top_padding             32
bspc config bottom_padding          35
bspc config left_padding            0
bspc config right_padding           0
bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config normal_border_color     "#0E446D"
bspc config focused_border_color    "#0978B4"
bspc config presel_feedback_color   "#0978B4"
#bspc config automatic_scheme        spiral

#bspc rule -a mplayer2 state=floating
#bspc rule -a conky state=fullscreen 
#conky -c $HOME/.conkyrc &
nitrogen --restore &
